// FOR MOVIES
export const SET_LOADING_MOVIES = "SET_LOADING_MOVIES";
export const GET_MOVIES = "GET_MOVIES";
export const GET_MOVIE = "GET_MOVIE";
export const GET_MOVIE_ACTORS = "GET_MOVIE_ACTORS";

// FOR TV SHOWS
export const SET_LOADING_TV = "SET_LOADING_MOVIES";
export const GET_TV_SHOWS = "GET_TV_SHOWS";
export const GET_TV_SHOW = "GET_TV_SHOW";
export const GET_TV_ACTORS = "GET_TV_ACTORS";
