// FOR MOVIES
export const SET_LOADING_MOVIES = "SET_LOADING_MOVIES";
export const GET_MOVIES = "GET_MOVIES";
export const GET_MOVIE = "GET_MOVIE";
export const GET_MOVIE_ACTORS = "GET_MOVIE_ACTORS";
export const GET_TOTAL_PAGES_MOVIES = "GET_TOTAL_PAGES_MOVIES";

// FOR TV SHOWS
export const SET_LOADING_TV = "SET_LOADING_MOVIES";
export const GET_TV_SHOWS = "GET_TV_SHOWS";
export const GET_TV_SHOW = "GET_TV_SHOW";
export const GET_TV_ACTORS = "GET_TV_ACTORS";
export const GET_TOTAL_PAGES_TV = "GET_TOTAL_PAGES_TV";

// FOR SEARCH
export const GET_SEARCH_RESULTS_MOVIES = "GET_SEARCH_RESULTS_MOVIES";
export const GET_SEARCH_RESULTS_TV = "GET_SEARCH_RESULTS_TV";
export const GET_TOTAL_PAGES_SEARCH_MOVIES = "GET_TOTAL_PAGES_SEARCH_MOVIES";
export const GET_TOTAL_PAGES_SEARCH_TV = "GET_TOTAL_PAGES_SEARCH_TV";
export const UPDATE_LOADING_SEARCH = "UPDATE_LOADING_SEARCH";
